[package]
name = "rusty_link"
version = "0.1.0"
authors = ["Andreas Mueller <anzbert@gmail.com>"]
edition = "2021"
description = "Plain Rust bindings for Ableton Link's C 11 Wrapper"
repository = "https://github.com/anzbert/rusty_link"
readme = "README.md"
license-file = "LICENSE.md"
keywords = ["ableton", "link"]
categories = ["api-bindings"]


[dependencies]
# Until PR to ffi_helpers has been accepted, this crate is using a fork
# which adds fn split_closure_trailing_data() and corresponding trait.
ffi_helpers = { git = "https://github.com/anzbert/ffi_helpers", branch = "pending", version = "0.3.01" }
# ffi_helpers = "^0.3.0"

[dev-dependencies]
ctrlc = "^3.2.3" # for link_hut example

[build-dependencies]
cmake = "^0.1.48"
bindgen = "^0.60.1"
