[package]
name = "rusty_link"
version = "0.3.2"
authors = ["Andreas Mueller <anzbert@gmail.com>"]
edition = "2021"
description = "Rust bindings for Ableton Link's C Wrapper Extension (abl_link)"
repository = "https://github.com/anzbert/rusty_link"
readme = "README.md"
license = "GPL-2.0-or-later"
keywords = ["ableton", "link"]
categories = ["api-bindings"]


[dependencies]

[dev-dependencies]
lazy_static = "^1.4.0"
crossterm = "^0.25.0"
cpal = "^0.14.0"       # See the cpal documentation for ASIO and Jack features

[build-dependencies]
cmake = "^0.1.48"
bindgen = "^0.61.0"
