[package]
name = "rusty_link"
version = "0.2.3"
authors = ["Andreas Mueller <anzbert@gmail.com>"]
edition = "2021"
description = "Rust bindings for Ableton Link's C Wrapper Extension (abl_link)"
repository = "https://github.com/anzbert/rusty_link"
readme = "README.md"
license = "GPL-2.0-or-later"
keywords = ["ableton", "link"]
categories = ["api-bindings"]


[dependencies]

[dev-dependencies]
lazy_static = "^1.4.0"
crossterm = "^0.25.0"  # Used in examples
cpal = "^0.14.0"       # Used in 'link_hut' example with sound (under development)

[build-dependencies]
cmake = "^0.1.48"
bindgen = "^0.61.0"
