[package]
name = "rusty_link"
version = "0.1.0"
authors = ["Andreas Mueller <anzbert@gmail.com>"]
edition = "2021"
description = "Plain Rust bindings for Ableton's Link C 11 Wrapper"
readme = "README.md"
license-file = "LICENSE.md"
repository = "https://github.com/anzbert/ableton-link-rs"
keywords = ["ableton", "link"]
categories = ["api-bindings"]


[dependencies]
# ffi_helpers = "^0.3.0"

# for now using a fork which reverses the order of
# ffi_helpers::split_closure()'s closure return type to trailing user_data
ffi_helpers = { git = "https://github.com/anzbert/ffi_helpers" }

[dev-dependencies]
ctrlc = "^3.2.3" # for link-hut example

[build-dependencies]
cmake = "^0.1.48"
bindgen = "^0.60.1"
